// Generated by CoffeeScript 1.10.0
(function() {
  var LineIter, randArrSel,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  randArrSel = function(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  };

  LineIter = (function() {
    function LineIter(grammar, vocab) {
      this.grammar = grammar;
      this.vocab = vocab;
      if (!(indexOf.call(this.grammar, "start") >= 0)) {
        throw new Error("StartError: No Start rule");
      }
      this.key = randArrSel(this.grammar.start);
      this.word = randArrSel(this.vocab[this.key]);
    }

    LineIter.prototype.checkIfEnd = function() {
      return this.word === "END";
    };

    return LineIter;

  })();

}).call(this);

//# sourceMappingURL=LineIter.js.map
