// Generated by CoffeeScript 1.10.0

/*
generates noun-verb phrases
 */

(function() {
  var i, j, nVGen, randArrSel, tester, voc;

  randArrSel = function(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  };

  nVGen = function(vocab) {
    return function() {
      return (randArrSel(vocab.nouns)) + " " + (randArrSel(vocab.verbs));
    };
  };

  voc = {
    nouns: ["bikes", "people", "lions", "thieves", "petals"],
    verbs: ["walk", "ran", "flew", "dove", "sighed", "love"]
  };

  tester = nVGen(voc);

  for (i = j = 0; j <= 20; i = ++j) {
    console.log(tester());
  }

}).call(this);

//# sourceMappingURL=snvgen.js.map
