// Generated by CoffeeScript 1.10.0
(function() {
  var WordIter, genPhrase, i, j, patterns, randArrSel, voc;

  randArrSel = function(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  };

  patterns = {
    start: ["noun_s", "det_s", "adj"],
    noun_s: ["verb_s", "verb_past", "END"],
    noun_p: ["verb_past", "END"],
    det_s: ["adj", "noun_s"],
    adj: ["noun_s"],
    verb_s: ["adv", "END"],
    verb_past: ["adv", "day", "END"],
    day: ["END"],
    adv: ["END"],
    END: ["END"]
  };

  voc = {
    noun_s: ["bat", "tree", "leaf", "love", "courage", "power"],
    noun_p: ["boats", "beasts", "skies", "pens", "papers"],
    det_s: ["the", "this", "that", "her", "his", "my"],
    verb_past: ["walked", "blinked", "died", "lived", "throbbed", "pounded", "fought"],
    verb_s: ["thinks", "talks", "looks", "travels", "bleeds"],
    adj: ["red", "big", "fast", "yellow", "dark"],
    day: ["today", "yesterday", "monday", "sunday"],
    adv: ["quickly", "abruptly", "cautiously", "happily", "sadly"]
  };

  WordIter = (function() {
    function WordIter(pat, vocab) {
      this.pat = pat;
      this.vocab = vocab;
      this.key = randArrSel(this.pat.start);
    }

    WordIter.prototype.nextWord = function() {
      var word;
      word = randArrSel(this.vocab[this.key]);
      this.key = randArrSel(this.pat[this.key]);
      return word;
    };

    return WordIter;

  })();

  genPhrase = function() {
    var gen;
    gen = new WordIter(patterns, voc);
    return ((function() {
      var results;
      results = [];
      while (gen.key !== "END") {
        results.push(gen.nextWord());
      }
      return results;
    })()).join(" ");
  };

  for (i = j = 0; j <= 10; i = ++j) {
    console.log(genPhrase() + ",");
  }

}).call(this);

//# sourceMappingURL=wordpats.js.map
