// Generated by CoffeeScript 1.10.0
(function() {
  var patterns;

  patterns = {
    start: ["noun_s", "det_s", "adj"],
    noun_s: ["verb_s", "verb_past", "END"],
    det_s: ["adj", "noun_s"],
    adj: ["noun_s"],
    verb_s: []
  };

}).call(this);

//# sourceMappingURL=wordpats.js.map
