// Generated by CoffeeScript 1.10.0
(function() {
  var patterns;

  patterns = {
    noun_s: ["verb_s", "verb_past", "punc", "END"],
    det_s: ["adj", "noun_s"],
    _ing: ["verb_s", "tobe_s"],
    tobe_s: ["adj", "END"]
  };

}).call(this);

//# sourceMappingURL=wordpats.js.map
