// Generated by CoffeeScript 1.10.0
(function() {
  var Haiku, Vocab, ptrns, vocabs;

  vocabs = require("./VocabManage");

  ptrns = require("./patterns.json");

  Vocab = require("./Vocab");

  Haiku = (function() {
    Haiku.randPatt = function(arr) {
      return arr[Math.floor(Math.random() * arr.length)];
    };

    function Haiku(voc) {
      var pat;
      this.patterns = [Haiku.randPatt(ptrns.syl_5), Haiku.randPatt(ptrns.syl_7), Haiku.randPatt(ptrns.syl_5)];
      this.vocab = new Vocab(vocabs[voc]);
      this.poem = ((function() {
        var i, len, ref, results;
        ref = this.patterns;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          pat = ref[i];
          results.push(this.genFromPattern(pat));
        }
        return results;
      }).call(this)).join("\n");
    }

    Haiku.prototype.genFromPattern = function(pat) {
      var field;
      return ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = pat.length; i < len; i++) {
          field = pat[i];
          results.push(this.vocab.randFromField(field));
        }
        return results;
      }).call(this)).join(" ");
    };

    Haiku.prototype.getPoem = function() {
      return this.poem;
    };

    return Haiku;

  })();

  module.exports = Haiku;

}).call(this);

//# sourceMappingURL=Haiku.js.map
