// Generated by CoffeeScript 1.10.0
(function() {
  var haiku, i, j;

  haiku = require("./Haiku");

  for (i = j = 0; j <= 6; i = ++j) {
    console.log((new haiku("test")).getPoem());
  }

}).call(this);

//# sourceMappingURL=Main.js.map
