// Generated by CoffeeScript 1.10.0
(function() {
  var Vocab,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Vocab = (function() {
    Vocab.BASE_FIELDS = ["1noun-s", "2noun-s", "3noun-s", "4noun-s", "1verb-s", "2verb-s", "3verb-s", "4verb-s", "1adv-s", "2adv-s", "3adv-s", "4adv-s", "1adj-s", "2adj-s", "3adj-s", "4adj-s", "1noun-p", "2noun-p", "3noun-p", "4noun-p", "1verb-p", "2verb-p", "3verb-p", "4verb-p", "1adv-p", "2adv-p", "3adv-p", "4adv-p", "1adj-p", "2adj-p", "3adj-p", "4adj-p"];

    function Vocab(dict) {
      if (typeof dict !== 'object' || dict === null) {
        throw new Error('Must load object as a vocab');
      }
      this.words = dict;
    }

    Vocab.prototype.validate = function(field) {
      return indexOf.call(this.words, field) >= 0;
    };

    Vocab.prototype.randFromField = function(field) {
      return this.words[field][Math.floor(Math.random() * this.words[field].length)];
    };

    return Vocab;

  })();

  module.exports = Vocab;

}).call(this);

//# sourceMappingURL=Vocab.js.map
